force-app/main/default/objects/Identity_Information__c/Identity_Information__c.object-meta.xml
<CustomObject>
    <description
  >Stores key information extracted from a South African ID number.</description>
    <label>Identity Information</label>
    <nameField>
        <displayFormat>ID-{00000000}</displayFormat>
        <label>Identity Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Identity Information</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Identity_Information__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <formula>DATE(
    IF(
        VALUE(LEFT(ID_Number__c, 2)) &gt;= (YEAR(TODAY()) - 2000),
        1900 + VALUE(LEFT(ID_Number__c, 2)),
        2000 + VALUE(LEFT(ID_Number__c, 2))
    ),
    VALUE(MID(ID_Number__c, 3, 2)),
    VALUE(MID(ID_Number__c, 5, 2))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Identity_Information__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <description>13-digit South African identity number</description>
    <externalId>true</externalId>
    <label>ID Number</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Identity_Information__c/fields/Search_Count__c.field-meta.xml
<CustomField>
    <fullName>Search_Count__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Number of searches for this ID number</description>
    <label>Search Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IDSearchController.cls
/*
*********************************************************
Apex Class Name    : IDSearchController
Created Date       : August 20, 2024
@description       : This class is used to search for and create 
					 ID Number records in Salesforce and retrieve 
					 holidays from an external service
@author            : Cornelia Smit
Modification Log:
Ver   Date         Author                        Modification
1.0   20-08-2024   Cornelia Smit                Initial Version
*********************************************************
*/
public with sharing class IDSearchController {
    @AuraEnabled
    public static String getHolidaysForID(String idNumber) {
        List<Identity_Information__c> idList = retrieveIdentityInformation(idNumber);
        String result = (idList.size() == 0) ? createIdentityInformation(idNumber) : incrementSearchCount(idList[0]);

        if(result != 'Success'){
            return result;
        }
        String holidays = 'Holidays';

        return holidays;
    }
    
    private static List<Identity_Information__c> retrieveIdentityInformation(String idNumber) {
        List<Identity_Information__c> idList = [SELECT Id, ID_Number__c, Search_Count__c, Date_of_Birth__c 
                                                FROM Identity_Information__c 
                                                WHERE ID_Number__c = :idNumber 
                                                WITH SECURITY_ENFORCED 
                                                LIMIT 1];
       return idList; 
    }
    
    private static String createIdentityInformation(String idNumber) {
        if(!Schema.sObjectType.Identity_Information__c.isCreateable()){
            return 'Error: Identity Information object is not createable';
        }
        Identity_Information__c newID = new Identity_Information__c();
        newID.ID_Number__c = idNumber;
        try {
            insert newID;
            return 'Success';
        } catch(DmlException e) {
            return 'Error: ' + e;
        }
    }
    
    private static String incrementSearchCount(Identity_Information__c idInfo) {
        if(!Schema.sObjectType.Identity_Information__c.isUpdateable() ||
           !Schema.sObjectType.Identity_Information__c.fields.Search_Count__c.isUpdateable()) {
            return 'Error: Identity Information record is not updateable';
        }
        
        idInfo.Search_Count__c = idInfo.Search_Count__c + 1;
        try {
            update idInfo;
            return 'Success';
        } catch(DmlException e) {
            return 'Error: ' + e;
        }
    }
}